version: "3.8"
services:

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dev
      - MYSQL_DATABASE=bagana
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bot:
    build: ./bot/
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=bagana
      - DB_TYPE=mariadb+mariadbconnector
      - WEB_PORT=8081
    ports:
      - 8081:8081
    depends_on:
      - db
    volumes:
      - ./bot/:/usr/src/app
    
     
